"""
Durable Job Queue using Redis Streams.

Provides at-least-once delivery semantics for background processing.
"""

import json
from abc import ABC, abstractmethod
from typing import Any, Dict, Optional

import structlog
from redis import asyncio as redis

from app.settings import settings

logger = structlog.get_logger(__name__)


class JobQueue(ABC):
    """Abstract interface for a job queue."""

    @abstractmethod
    async def enqueue(self, job_name: str, payload: Dict[str, Any]) -> str | None:
        """Enqueues a job with a name and data."""
        pass


class RedisStreamsQueue(JobQueue):
    """
    Job queue implementation using Redis Streams (XADD).

    This provides durability and allows multiple consumers via Consumer Groups.
    """

    def __init__(self, redis_url: str, stream_name: str = "contact_jobs"):
        self.redis_url = redis_url
        self.stream_name = stream_name
        self._redis: Optional[redis.Redis] = None

    async def _get_client(self) -> redis.Redis:
        if self._redis is None:
            self._redis = redis.from_url(
                self.redis_url,
                encoding="utf-8",
                decode_responses=True,
                socket_timeout=5,
                retry_on_timeout=True,
            )
        return self._redis

    async def enqueue(self, job_name: str, payload: Dict[str, Any]) -> str | None:
        """Pushes a job to the Redis Stream."""
        try:
            client = await self._get_client()
            # XADD: StreamName, MaxLen (approx), ID (autogenerated), Fields...
            job_id = await client.xadd(
                self.stream_name,
                {"job_name": job_name, "payload": json.dumps(payload)},
                maxlen=10000,  # Prevent stream from growing indefinitely
                approximate=True,
            )
            logger.info("job_enqueued", job_name=job_name, job_id=job_id)
            return job_id
        except Exception as e:
            logger.error("job_enqueue_failed", job_name=job_name, error=str(e))
            # If Redis fails, we raise to trigger the fail-closed/open logic in the controller
            raise


# Global instance for easy access if needed, or inject via DI
queue = RedisStreamsQueue(settings.redis_url) if settings.redis_url else None
