"""
Durable Job Queue using Redis Streams.

Provides at-least-once delivery semantics for background processing.
"""

import json
from datetime import datetime, timezone
from abc import ABC, abstractmethod
from typing import Any, Dict

import structlog
from redis import asyncio as redis

from app.core.infrastructure import get_redis
from app.settings import settings

logger = structlog.get_logger(__name__)


class JobQueue(ABC):
    """Abstract interface for a job queue."""

    @abstractmethod
    async def enqueue(self, job_name: str, payload: Dict[str, Any]) -> str | None:
        """Enqueues a job with a name and data."""
        pass


class RedisStreamsQueue(JobQueue):
    """
    Job queue implementation using Redis Streams (XADD).

    This provides durability and allows multiple consumers via Consumer Groups.
    """

    DLQ_STREAM = "contact_jobs_dlq"

    def __init__(self, redis_url: str, stream_name: str = "contact_jobs"):
        self.redis_url = redis_url
        self.stream_name = stream_name
        self.max_stream_len = 10000
        self.max_dlq_len = 5000

    async def _get_client(self) -> redis.Redis:
        return get_redis()

    def _build_metadata(self) -> Dict[str, Any]:
        now = datetime.now(timezone.utc).isoformat()
        return {
            "retry_count": 0,
            "first_seen_at": now,
            "last_attempt_at": None,
            "last_error": None,
            "last_error_type": None,
            "failure_class": None,
        }

    def _validate_job(self, job_name: str, payload: Dict[str, Any]) -> None:
        if not job_name or not isinstance(payload, dict):
            raise ValueError("job_name and payload are required")

    async def enqueue(self, job_name: str, payload: Dict[str, Any]) -> str | None:
        """Pushes a job to the Redis Stream."""
        try:
            self._validate_job(job_name, payload)
            client = await self._get_client()
            body = {
                "job_name": job_name,
                "payload": payload,
                "meta": self._build_metadata(),
            }
            # XADD: StreamName, MaxLen (approx), ID (autogenerated), Fields...
            job_id = await client.xadd(
                self.stream_name,
                {"job_name": job_name, "payload": json.dumps(body)},
                maxlen=self.max_stream_len,
                approximate=True,
            )
            logger.info("job_enqueued", job_name=job_name, job_id=job_id)
            return job_id
        except Exception as e:
            logger.error("job_enqueue_failed", job_name=job_name, error=str(e))
            # If Redis fails, we raise to trigger the fail-closed/open logic in the controller
            raise

    async def enqueue_dlq(
        self,
        *,
        job_name: str,
        payload: Dict[str, Any],
        metadata: Dict[str, Any],
        reason: str,
        error_type: str,
    ) -> str | None:
        """Publishes a failed job to the DLQ stream with failure context."""
        try:
            self._validate_job(job_name, payload)
            client = await self._get_client()
            metadata["last_error"] = reason
            metadata["last_error_type"] = error_type
            body = {"job_name": job_name, "payload": payload, "meta": metadata}
            job_id = await client.xadd(
                self.DLQ_STREAM,
                {"job_name": job_name, "payload": json.dumps(body)},
                maxlen=self.max_dlq_len,
                approximate=True,
            )
            logger.info(
                "job_published_dlq",
                job_id=job_id,
                reason=reason,
                error_type=error_type,
            )
            return job_id
        except Exception as e:
            logger.error(
                "job_publish_dlq_failed",
                job_name=job_name,
                reason=reason,
                error_type=error_type,
                error=str(e),
            )
            raise


# Global instance for easy access if needed, or inject via DI
queue = RedisStreamsQueue(settings.redis_url) if settings.redis_url else None
